version: 2
jobs:
  build:
  working_directory: ~/myapp/angular-wishlist
  docker:
    - image: circleci/node:8-browsers
  steps:
    - checkout:
        path: ~/myapp
    - restore_cache:
    - run: npm install
    - save_cache:
        paths:
          - "node_modules"
    - run: npm run test -- --progress=false --watch=false --browsers=ChromeHeadlessCI
